#!/bin/sh /etc/rc.common

# menu-move - regenerate the LuCI menu overrides.
#
# There is no daemon: "start" builds /usr/share/luci/menu.d/zz-luci-app-menuMove.json
# and the procd config trigger re-runs it whenever /etc/config/menu-move changed
# (that is what uci commit / "Save & Apply" in the web interface triggers).

START=95
STOP=10
USE_PROCD=1

apply_rules() {
	/usr/bin/menu-move apply >/dev/null 2>&1
	return 0
}

start_service() {
	apply_rules
}

reload_service() {
	apply_rules
	logger -t menu-move "menu overrides regenerated"
}

stop_service() {
	return 0
}

service_triggers() {
	procd_add_reload_trigger "menu-move"
}

boot() {
	start "$@"
}
